[project]
name = "classmate"
version = "0.1.0"
description = "Meeting transcription and review tool"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = "==3.11.9"
dependencies = [
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "rich>=13.0.0",
    "soundfile>=0.12.1",
    "soundcard (>=0.4.5,<0.5.0)",
    "numpy (<2.0.0)",
]


[tool.poetry]
packages = [
    { include = "classmate", from = "source" }
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
